#!/usr/bin/env php
<?php
/**
 * Dotz setup script.
 * Could later be used for handling updates.
 */

require 'vendor/autoload.php';

use Symfony\Component\Console\Application;
use DotzFramework\CLI\SetupCommand;

$application = new Application();

// ... register commands
$application->add(new SetupCommand());


$application->run();