#!/usr/bin/env php
<?php
//ini_set('display_errors', 1);
//error_reporting(E_ALL & ~E_DEPRECATED & ~E_STRICT & ~E_NOTICE);

//require '../../autoload.php';
require 'vendor/autoload.php';

use Symfony\Component\Console\Application;
use DotzFramework\CLI\SetupCommand;

$application = new Application();

// ... register commands
$application->add(new SetupCommand());


$application->run();